[alembic]
# path to migration scripts
script_location = alembic
# template used to generate migration file names
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s
# timezone to use when rendering the date
# timezone =
# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40
# sqlalchemy.url is set dynamically in env.py, but required here for fallback
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost/visionguard

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
